name: MinecraftMusicManager
main: com.minecraftmusicmanager.MinecraftMusicManager
version: 1.0
api-version: 1.21
commands:
  minecraftmusicmanager:
    description: Reloads the plugin
    usage: /<command> reload
    permission: minecraftmusicmanager.admin
permissions:
  minecraftmusicmanager.admin:
    description: Allows using /minecraftmusicmanager reload
    default: op
